const $=s=>document.querySelector(s);let activeTab=null,allCookies=[];const toast=m=>{const t=$('#toast');t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)};
function parseHeader(input){return input.split(/;\s*/).map(x=>x.trim()).filter(Boolean).map(x=>{const i=x.indexOf('=');if(i<1)return null;return {name:x.slice(0,i).trim(),value:x.slice(i+1).trim()}}).filter(Boolean)}
async function getTab(){const tabs=await chrome.tabs.query({active:true,currentWindow:true});return tabs[0]}
function render(){const q=$('#search').value.toLowerCase();const rows=$('#rows');rows.textContent='';allCookies.filter(c=>`${c.name} ${c.domain}`.toLowerCase().includes(q)).forEach(c=>{const tr=document.createElement('tr');for(const [k,v] of [['name',c.name],['domain',c.domain],['value',c.value]]){const td=document.createElement('td');td.className=k==='value'?'value':'';td.textContent=k==='value'?(c.value.length>18?c.value.slice(0,8)+'••••'+c.value.slice(-6):c.value):v;tr.appendChild(td)}const td=document.createElement('td');const b=document.createElement('button');b.textContent='Delete';b.onclick=async()=>{try{await chrome.cookies.remove({url:`${c.secure?'https':'http'}://${c.domain.replace(/^\\./,'')}${c.path}`,name:c.name});toast('Cookie deleted');load()}catch(e){toast(e.message)}};td.appendChild(b);tr.appendChild(td);rows.appendChild(tr)})}
async function load(){activeTab=await getTab();if(!activeTab?.url||!/^https?:\/\//.test(activeTab.url)){allCookies=[];$('#domain').textContent='Open facebook.com in the active tab';render();return}const u=new URL(activeTab.url);$('#domain').textContent=u.hostname;allCookies=await chrome.cookies.getAll({domain:u.hostname});render()}
$('#search').oninput=render;$('#refresh').onclick=load;$('#clearInput').onclick=()=>$('#cookieInput').value='';
$('#apply').onclick=async()=>{try{if(!activeTab?.url)throw Error('No supported active tab');const u=new URL(activeTab.url);if(!/^(www\.)?facebook\.com$|\.facebook\.com$/.test(u.hostname))throw Error('Open facebook.com first');const list=parseHeader($('#cookieInput').value);if(!list.length)throw Error('No valid cookies found');let ok=0,fail=0;for(const c of list){try{await chrome.cookies.set({url:u.origin+'/',name:c.name,value:c.value,path:'/'});ok++}catch(e){fail++}}await load();toast(`Applied ${ok} cookie(s)${fail?`; ${fail} failed`:''}`)}catch(e){toast(e.message)}};
$('#export').onclick=()=>{const blob=new Blob([JSON.stringify(allCookies,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='facebook-cookies.json';a.click();URL.revokeObjectURL(a.href)};
$('#reload').onclick=()=>activeTab&&chrome.tabs.reload(activeTab.id);load();
